export function UseCases() {
  const cards = [
    {
      label: "For Builders",
      title: "Builders & small teams",
      body: "Ship complex architectures at full speed without walking into classic distributed systems landmines. Get the architectural instincts of a senior principal engineer in your prompt terminal.",
      arrow: "→ Zero architectural regression",
    },
    {
      label: "For Platform Leads",
      title: "Platform & engineering leads",
      body: "Enforce standardized tech stack compliance, control model invocation spend across teams, and ensure code generated by AI follows internal architectural mandates automatically.",
      arrow: "→ Strict stack governance",
    },
    {
      label: "For Compliance",
      title: "Compliance & risk teams",
      body: "Cryptographically signed execution trails. Pre-commit data governance reviews that catch PII leaks, licensing infractions, and unsecured endpoints before merge requests exist.",
      arrow: "→ Continuous tamper-evident audit",
    },
  ];

  return (
    <section className="section-pad bg-surface">
      <div className="mx-auto max-w-6xl">
        <div className="mb-4 text-center text-xs uppercase tracking-[0.5px] text-muted">
          Use Cases
        </div>
        <h2 className="mb-12 text-center text-3xl font-bold leading-tight sm:text-4xl">
          Built for every role in the room.
        </h2>
        <div className="mx-auto grid gap-6 md:grid-cols-3">
          {cards.map((c) => (
            <div
              key={c.title}
              className="rounded-lg border border-line bg-bg p-6 transition-all hover:-translate-y-2 hover:border-muted hover:shadow-lg"
            >
              <div className="mb-3 text-[11px] font-semibold uppercase tracking-[0.5px] text-muted">
                {c.label}
              </div>
              <h3 className="mb-4 text-xl font-semibold">{c.title}</h3>
              <p className="mb-4 text-sm leading-relaxed text-muted">{c.body}</p>
              <div className="flex items-center gap-2 font-semibold">{c.arrow}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
