// Legal documents (F49) — plain-language ToS, Privacy Policy, and Refund Policy.
// Rendered by /legal/[doc]; linked from the signup flow and the footer.

export type LegalSection = { heading: string; body: string[] };
export type LegalDoc = {
  slug: string;
  title: string;
  description: string;
  updated: string;
  sections: LegalSection[];
};

export const LEGAL_DOCS: Record<string, LegalDoc> = {
  terms: {
    slug: "terms",
    title: "Terms of Service",
    description: "The terms that govern your use of Verya.",
    updated: "2026-09-18",
    sections: [
      {
        heading: "1. Acceptance of terms",
        body: [
          "By accessing or using Verya (the \"Service\"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use the Service.",
          "If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these terms.",
        ],
      },
      {
        heading: "2. What the Service does",
        body: [
          "Verya analyzes software project descriptions and workflows, flags flaws, recommends stacks, algorithms, and AI models, and executes tasks through third-party AI providers. Every decision is recorded in an append-only audit ledger.",
          "Verya provides decision support and verification. It does not guarantee that generated plans or outputs are free of defects, and it is not a substitute for professional engineering judgment.",
        ],
      },
      {
        heading: "3. Your responsibilities",
        body: [
          "You are responsible for the accuracy of the content you submit, for reviewing outputs before acting on them, and for complying with all laws applicable to your use of the Service.",
          "You may not submit content that is unlawful, infringing, or that attempts to reverse-engineer, overload, or disrupt the Service or its providers.",
        ],
      },
      {
        heading: "4. Third-party AI providers",
        body: [
          "The Service routes work to third-party AI model providers (such as Google, Groq, Mistral, and OpenRouter). Your use of outputs generated by those models is additionally subject to the applicable provider terms.",
          "Provider availability is outside our control; the Service includes failover mechanisms but cannot guarantee any specific model remains available.",
        ],
      },
      {
        heading: "5. Intellectual property",
        body: [
          "You retain ownership of the content you submit. You grant Verya a limited license to process that content solely to provide the Service.",
          "Verya retains all rights in the Service itself, including software, branding, and documentation.",
        ],
      },
      {
        heading: "6. Disclaimers and limitation of liability",
        body: [
          "The Service is provided \"as is\" without warranties of any kind, express or implied. To the maximum extent permitted by law, Verya's total liability arising out of or relating to the Service is limited to the amounts you paid to Verya in the twelve months preceding the claim, or USD 100 if you have not paid any amounts.",
          "Verya is not liable for indirect, incidental, special, consequential, or punitive damages, including lost profits or data, even if advised of the possibility of such damages.",
        ],
      },
      {
        heading: "7. Termination and changes",
        body: [
          "You may stop using the Service at any time. We may suspend or terminate access for violation of these terms, or modify the Service and these terms with reasonable notice. Continued use after changes take effect constitutes acceptance.",
        ],
      },
      {
        heading: "8. Governing law and contact",
        body: [
          "These terms are governed by the laws of the jurisdiction in which Verya's operating entity is registered, without regard to conflict-of-law rules.",
          "Questions about these terms can be sent to legal@verya.app.",
        ],
      },
    ],
  },
  privacy: {
    slug: "privacy",
    title: "Privacy Policy",
    description: "How Verya collects, uses, and protects your data.",
    updated: "2026-09-18",
    sections: [
      {
        heading: "1. Data we collect",
        body: [
          "Account data: your name, email address, and organization membership as provided through authentication (Clerk).",
          "Project data: the project descriptions, files, and workflow decisions you submit, plus the AI outputs, verifications, and human accept/edit/reject decisions produced as you use the Service.",
          "Operational data: an append-only audit ledger recording which models were used, what they produced, and how humans responded. This ledger exists to make AI use auditable; it is described in our Trust Ledger documentation.",
          "Lead data: if you submit the contact form, your name, email, and phone number.",
        ],
      },
      {
        heading: "2. How we use data",
        body: [
          "To operate the Service: routing tasks to AI models, verifying outputs, and maintaining your organization's private memory so future routing decisions improve.",
          "To provide governance features: reputation scoring, escalation, and audit reporting are computed from your organization's own records and stay partitioned per organization.",
          "We do not sell personal data, and we do not use your project data to advertise to you.",
        ],
      },
      {
        heading: "3. AI providers and sharing",
        body: [
          "Project content is sent to third-party AI model providers solely to execute the tasks you approve. Providers process content under their own terms and privacy policies.",
          "We share data only with the providers necessary to deliver the Service, with infrastructure vendors (database, caching), and when required by law.",
        ],
      },
      {
        heading: "4. Data location, retention, and your controls",
        body: [
          "Data is stored in Neon PostgreSQL. Audit ledger records are append-only and retained per your organization's retention configuration; memory records can be exported or fully deleted by an organization admin at any time from the dashboard.",
          "You may request export or deletion of your organization's data by contacting privacy@verya.app. We will respond within 30 days.",
        ],
      },
      {
        heading: "5. Security",
        body: [
          "All traffic is encrypted in transit (TLS). Database access requires authenticated connections. Secrets are stored in environment configuration, never in the application database, and are never exposed to the browser.",
          "Every ledger record is hash-chained so tampering is detectable, and the chain can be verified at any time.",
        ],
      },
      {
        heading: "6. Cookies and tracking",
        body: [
          "Verya uses strictly necessary browser storage (theme preference, draft input, session identifier). We do not use advertising trackers. If analytics are enabled, they are aggregate and privacy-respecting; a consent notice will be shown where required by law.",
        ],
      },
      {
        heading: "7. Contact",
        body: ["Privacy questions or requests: privacy@verya.app."],
      },
    ],
  },
  refunds: {
    slug: "refunds",
    title: "Refund Policy",
    description: "How refunds and cancellations work at Verya.",
    updated: "2026-09-18",
    sections: [
      {
        heading: "1. Free tier",
        body: [
          "Verya's core pipeline is available on a free evaluation basis while the product is in early access. Charges only apply to paid plans once billing is enabled for your account, and you will always see the price before you are charged.",
        ],
      },
      {
        heading: "2. Paid plans",
        body: [
          "If you purchase a subscription, you may cancel at any time; cancellation stops future billing cycles and the Service remains available through the end of the paid period.",
          "Refunds for the current billing period are available within 14 days of the charge if you have not consumed a disproportionate share of the period's included usage. Beyond 14 days, charges for the current period are non-refundable but never renew.",
          "Approved refunds are returned to the original payment method within 10 business days.",
        ],
      },
      {
        heading: "3. Service failures",
        body: [
          "If a paid billing period was substantially unavailable due to a failure on our side, contact billing@verya.app with the affected dates. We will credit or refund the affected period pro rata, regardless of the 14-day window above.",
        ],
      },
      {
        heading: "4. How to request a refund",
        body: [
          "Email billing@verya.app from your account address with the invoice ID and reason. We acknowledge every request within 2 business days and aim to resolve within 5.",
        ],
      },
    ],
  },
};

export function isLegalSlug(slug: string): boolean {
  return Object.prototype.hasOwnProperty.call(LEGAL_DOCS, slug);
}
